### ISSUE TITLE
Architecture 3.0

### ISSUE THREAD

**Issue by AtiX** [brickify/brickify#413]
- [x] Extract csg to own plugin (see #426 )
- [x] Extract export plugin
- [x] Extract edit controller (see #414 )
- ...

![2015-03-27 architecture restructuring 3](https://cloud.githubusercontent.com/assets/236678/6942633/28652320-d889-11e4-9b43-b91233ead162.jpg)
![2015-03-27 architecture restructuring 1](https://cloud.githubusercontent.com/assets/236678/6942619/18679174-d889-11e4-9f97-91a3f7d88eaf.jpg)
![2015-03-27 architecture restructuring 2](https://cloud.githubusercontent.com/assets/236678/6942618/1867aa06-d889-11e4-9ef8-bd1eb4dffd71.jpg)

**Comment by Steditor** [comment]
I think this is all done by now...
