### ISSUE TITLE
brick layouter is biased towards one direction

### ISSUE THREAD

**Issue by stuikomma** [brickify/brickify#482]
Note that the left side has always 1 brick per layer but the front side is fragmented a lot. It should be distributed more equally .

![image](https://cloud.githubusercontent.com/assets/2040603/7294295/3323947a-e9ac-11e4-9495-72dfc2ff6ba2.png)

**Comment by johannesdeselaers** [comment]
update:
I am still not able to figure out why this occurs, will be focusing on this issue now
currently occurs in 3 Layer merges aswell:
![directionbugsmall](https://cloud.githubusercontent.com/assets/1779611/8129537/61862028-110a-11e5-9e2d-e3b9154801b5.PNG)

**Comment by johannesdeselaers** [comment]
for the record, the preferred direction of long bricks is along the y axis
