### ISSUE TITLE
Rebrand to brickify.it

### ISSUE THREAD

**Issue by AtiX** [brickify/brickify#485]
- [x] names (see #486 )
- [x] impressum (see #478 )
- [x] contribute (see #487 )
- [x] piwik settings
- [x] rename project, GitHub organisation ( see #490 )
- [x] update domains to dev.brickify.net / brickify.net
- [x] redirect page from lowfab -> brickify
- [x] add brickify.it to google webmaster tools / bing index
- [x] update feedback form

**Comment by Steditor** [comment]
One last thing open: redirection from lowfab to brickify. @AtiX ?
