### ISSUE TITLE
can't LEGO-brush 3D geometry in mid air

### ISSUE THREAD

**Issue by stuikomma** [brickify/brickify#572]
Take this model as an example:
![image](https://cloud.githubusercontent.com/assets/2040603/8053974/5b7aa112-0e95-11e5-92c3-096a2c365165.png)

1. convert all to 3D
2. select LEGO brush (or use right click)
3. brush the handle in the middle -> nothing happens

You should be able to brush the handle starting in the middle of the handle.

**Comment by adius** [comment]
I think it should start at the bottom of the handle and not in the middle

**Comment by Steditor** [comment]
At least as long as the lego board is below the pointer.

**Comment by stuikomma** [comment]
Can't reproduce. Now it works as expected.
