### ISSUE TITLE
Ensure distinct coloring of neighbors

### ISSUE THREAD

**Issue by Steditor** [brickify/brickify#574]
The instructions are hard to read, sometimes it is impossible to recognize the individual bricks within a layer.

**Comment by johannesdeselaers** [comment]
this is done partially here: https://github.com/brickify/brickify/blob/9f6bd2ded1eb0db9e7acd7010f493e5aa95ad24e/src/plugins/nodeVisualizer/visualization/Coloring.coffee#L155
however it uses randomness and may fail, we should find another method

**Comment by johannesdeselaers** [comment]
the getNeighbors method used was outdated, should be ok now
