### ISSUE TITLE
Solve usability problem: Left Mouse Button rotates and brushes

### ISSUE THREAD

**Issue by AtiX** [brickify/brickify#587]
Although user get the idea of both modes and can control it,
it happens (in the heat of the moment) that they accidently try to rotate with the mouse over the model, therefore brushing right over it.

Ideas: modifier keys (but make the overall concept more difficult...)

**Comment by Steditor** [comment]
Modifier keys would make it impossible to be used on touch devices.
I'd simply go with a undo, see #249

**Comment by AtiX** [comment]
(Y)

**Comment by Steditor** [comment]
Will be done in #249
