### ISSUE TITLE
Recheck Renderer.setFidelity

### ISSUE THREAD

**Issue by Steditor** [brickify/brickify#625]
In [L195](https://github.com/brickify/brickify/blob/develop/src/client/rendering/Renderer.coffee#L195) the method checks whether `@pipelineEnabled` is true.

But [the fidelity control](https://github.com/brickify/brickify/blob/develop/src/plugins/fidelityControl/fidelityControl.coffee#L130) always calls the method before setting `@pipelineEnabled` - probably because in [L57](https://github.com/brickify/brickify/blob/develop/src/client/rendering/Renderer.coffee#L57) the check must not be true before having set up all the things in `setFidelity`.

I wonder whether these setups might come one fidelity adjustment too late, because `setFidelity` works on the previous value of `@pipelineEnabled`. Everything works now, because we never change the fidelity level by more than one or (in case of the instructions) toggle between the exact previous level and DH.

**Comment by stuikomma** [comment]
It works accidentally because in `setFidelity` there is nothing specific to `'PipelineLow'`. So when the fidelity is set to `'PipelineMedium'` `@pipelineEnabled` is already set to true. Will be fixed when merging gracefully_uglify_brickVisualization. PR will follow tomorrow.
