### ISSUE TITLE
Relayout causes infinite loop

### ISSUE THREAD

**Issue by stuikomma** [brickify/brickify#643]
Sometimes when brushing the whole page hangs. It happens while running the step `local relayout`.

**Comment by AtiX** [comment]
It is the step Local reLayout,
see screenshot of crashed page:

![capture](https://cloud.githubusercontent.com/assets/236678/8303390/e163dace-199d-11e5-8e58-3c5f165721b3.PNG)

**Comment by johannesdeselaers** [comment]
that was tricky
it occurs when all bricks to be relayouted get merged into bricks with z = 3, so the plate layout pass has no bricks to work on
pull request with fix is on the way
