### ISSUE TITLE
Layouter is too greedy

### ISSUE THREAD

**Issue by AtiX** [brickify/brickify#644]
1. Make everything 3d-print
2. brush the bottom layer of the object (e.g. cube.stl) with the make lego brush
3. often: 3-layered bricks are generated even though not all of these layers were selected for LEGO

**Comment by AtiX** [comment]
Only the bottom voxel layer was selected: 

![capture](https://cloud.githubusercontent.com/assets/236678/8303620/7236ebbc-199f-11e5-8c13-6f3d68723c81.PNG)

**Comment by johannesdeselaers** [comment]
hmm, i've been able to reproduce this once (out of about 70 tries), i.e. it's pretty hard to debug that way
any particular way you were brushing that causes the issue more often?

**Comment by stuikomma** [comment]
Just brush the ground level in one stroke. Worked every time. Make sure to brush only that layer and no voxel in layer 1.

**Comment by johannesdeselaers** [comment]
there seems to be a general issue when placing LEGO at a voxel not connected to any other curretly existing LEGO
i am still searching for the root cause

**Comment by johannesdeselaers** [comment]
update:
i believe the error only occurs after using the 'make everything 3D-print' functionality (please verify)
the reinitialization of the grid seems broken, still figuring out why

**Comment by johannesdeselaers** [comment]
replaced by #682
